version: '3.9'
services:
  web:
    build: ./weather/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/weather/
    ports:
      - 0.0.0.0:8000:8000
    depends_on:
      - db

  db:
    image: postgres:15.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=userAdmin
      - POSTGRES_DB=weather
    ports:
      - 5432:5432

volumes:
  postgres_data:
  